version: '3.8'

services:
    dev:
        container_name: mailer_dev
        image: mailer-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn dev
        expose:
            - ${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped