import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '@components/Layout/Layout'
import { CssBaseline } from '@mui/material'
import { ThemeProvider } from '@emotion/react'
import { Theme } from 'helpers/theme'
import Head from 'next/head'
import { SnackbarProvider } from 'notistack';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<ThemeProvider theme={Theme}>
			<SnackbarProvider maxSnack={3}>
				<Head>
					<title>Email Automation</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<CssBaseline />
				<Layout>
					<Component {...pageProps} />
				</Layout>
			</SnackbarProvider>
		</ThemeProvider>
	)
}

export default MyApp
