import Head from 'next/head'
import React, { ReactElement, useEffect } from 'react'
import { AppProps } from 'next/app'
import { ThemeProvider } from '@emotion/react'
import { CssBaseline } from '@mui/material'
import { ToastContainer } from 'material-react-toastify';
import { Theme } from 'helpers/theme'
import BasicLayout from '@components/Layout/Layout'
import PageWithLayoutType from 'types/pageWithLayouts'
import '../styles/globals.scss'
import 'material-react-toastify/dist/ReactToastify.css';
import { observer } from 'mobx-react'
import AuthStore from '@stores/AuthStore'
import { useRouter } from 'next/router'

type AppLayoutProps = AppProps & {
	Component: PageWithLayoutType
	pageProps: any
}

function MyApp({ Component, pageProps }: AppLayoutProps) {
	const Layout = Component.layout ? Component.layout : BasicLayout || ((children: ReactElement) => <>{children}</>)
	const router = useRouter();

	useEffect(()=> {
		if (!AuthStore.isLoggedIn) router.push('/auth/login')
	// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [AuthStore.isLoggedIn])

	return (
		<ThemeProvider theme={Theme}>
			<ToastContainer />
			<Head>
				<title>Email Automation</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CssBaseline />
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</ThemeProvider>
	)
}

export default observer(MyApp)
